format = '$git_branch$directory$battery$time$status$shell$character'

[directory]
format='[ğŸ—‚ï¸  $path]($style)[$read_only]($read_only_style) '
style='fg:#2f1c1e bg:#b5ffa9'

[aws]
format=''

[docker_context]
format=''

[git_branch]
format='[ğŸŒ± $branch(:$remote_branch)]($style) '
style='bg:#2f1c1e fg:#b5ffa9'
