format = """
[â”‚](bold fg:63)$kubernetes$terraform$directory$git_branch
[â””â”€>](bold fg:63) """

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸ£ "
style="bold fg:105"

[directory]
truncation_symbol = "ğŸ“.../"
truncation_length = 16
format = "[$path]($style)[$lock_symbol]($lock_style) "

[kubernetes]
format = '[â˜¸ï¸  k8s: $context](green) '
disabled = false

[terraform]
format = '[$symbol$workspace]($style) '
disabled = false

[package]
disabled = true
